(function (global, factory) {
    if (typeof define === "function" && define.amd) {
        define(['module', './panelgroup'], factory);
    } else if (typeof exports !== "undefined") {
        factory(module, require('./panelgroup'));
    } else {
        var mod = {
            exports: {}
        };
        factory(mod, global.panelgroup);
        global.tabs = mod.exports;
    }
})(this, function (module) {
    'use strict';

    var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
        return typeof obj;
    } : function (obj) {
        return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
    };

    (function (factory) {
        if ((typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object' && module.exports) {
            module.exports = factory();
        } else {
            factory();
        }
    })(function () {
        'use strict';

        //Tabs is generated by panelgroup

        return rb.components.tabs;
    });
});
