(function (factory) {
    if (typeof module === 'object' && module.exports) {
        require('../rb_panelgroup/rb_panelgroup');
        module.exports = factory();
    } else {
        factory();
    }
}(function () {
    'use strict';

    //Tabs is generated by panelgroup
    return rb.components.tabs;
}));
