(function (factory) {
    if (typeof module === 'object' && module.exports) {
        require('./panelgroup');
        module.exports = factory();
    } else {
        factory();
    }
}(function () {
    'use strict';

    //Acccordion is generated by panelgroup
    return rb.components.accordion;
}));
